### ISSUE TITLE
Participant identity verification duplicate flag set but system allowed to sign up as active participant

### ISSUE THREAD

**Issue by dbakumar** [episphere/connectApp#57]
this issue is happen when active participant  who received PIN in the letter but not used their assigned PIN for first time enrollment and IHCS site verified as passive participant since possible match found & send duplicate flag to original assigned token.  After few hours he/she created another signup but submitted PIN in the letter.   PWA app should not allow to proceed as active participant but its allowed.

Steps to regenerate this issue:

1. Generate token/PIN for a study id
2. IHCS Set duplicate flag  for generated token (step1)
3. Use PIN  (step1) to signup 

 
![image](https://user-images.githubusercontent.com/4921186/114771764-99408480-9d32-11eb-95ba-a8e412aea498.png)

**Comment by FrogGirl1123** [comment]
@dbakumar  Hi Vijay, First a question, then a comment.  1) Did you update the participants status to "active" during the verification process after you found that you had a token for them? 2) Because the participant did not use their PIN when they enrolled the first time, the PWA would have no way of knowing that this person had previously enrolled and was verified.  The PWA only assigns a new token if the PIN has been used before or if the participant comes in without a PIN or a Token.  In the  scenario you described, the participant would complete enrollment through the user profile as an active participant and possibly start the questionnaires.   When this record is called by your system, you would flag it as a duplicate (multiple accounts scenario) and the participant would receive a message to that effect for that account.

**Comment by FrogGirl1123** [comment]
We have office hours this week if you have any follow-up questions

**Comment by dbakumar** [comment]
Hi @FrogGirl1123 ,  sorry I am just seeing this message.   my understanding, we need to check token exist and also **shouldn't have duplicate flag** when the participant signup with token or PIN.  the above mentioned scenario, the second time also participant enrolled as passive recruit.

scenario detail :  

1. IHCS send letter with PIN
2. Participant find Connect Study website through Google search and than signup using email,  answers "i don't have PIN" , select HealthPartners as a care system,  complete consent & User profile.  (First time participant sign-in as **Passive recruit**)
3. IHCS identity verification  process identify as Passive recruit manual review. 
4. As part of IHCS identity verification process: 
    4.1 participant possible match found in IHCS CRM record but  already assigned token (active recruit) is not match because of PIN not used.  
    4.2 _program send duplicate flag to already assigned token (active recruit) in IHCS CRM_
    4.3 program take new token (**Passive recruit** ) from participant NCI record and save to IHCS CRM. 

5. After few hours, Participant find letter with PIN, he/she thought  better to use PIN  with Connect study website. 
6. Second time participant sign up using phone number, enter the PIN, complete consent & User profile. 

On step 6 - it should not allowed to use the PIN which sent in letter because IHCS already sent duplicate flag to original assigned token/PIN(step 4.2).

**Comment by FrogGirl1123** [comment]
@dbakumar Hi Vijay, I think we covered this on the F&R office hours call yesterday, but if you have any follow-up questions let me know.
