### ISSUE TITLE
Invalid Concept ID Captured for "Suffix"

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connectApp#632]
Connect IDs 7632967928, 7314631953, 8762588004, 6533631172, and 8674499244 have a value of "398561594" for Suffix (d_506826178) which is not a valid option for this variable.

**Comment by brotzmanmj** [comment]
Amelia tracked down the source of this decision. It applies to user profile changes only.
If a suffix was originally entered and then upon editing the User Profile it was deleted, then it is coded this way:
-suffix removal writes value as a number (conceptId 398561594) 
This signifies 'none of the above' rather than reverting it to null.

@mnataraj92  we suggest making a note in the DD for the Suffix UP variable only that this is an allowable code but is not present on the dropdown as a visible choice; it is back end coded only in the instance where the UP is edited and a previously entered suffix is removed. And then we can remove it from the QC check since it's an allowable response?

Thanks!

**Comment by mnataraj92** [comment]
Will do!
